server {
  listen 80;

  location / {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri $uri/ /index.html;
  }

  location /health {
    return 200 "ok";
    add_header Content-Type text/plain;
  }

  location /api {
    proxy_pass http://api-gateway:8000;
  }

  location /simulate {
    proxy_pass http://api-gateway:8000;
  }

  location /stream {
    proxy_pass http://api-gateway:8000;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_buffering off;
    proxy_cache off;
  }
}
