global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']
    metrics_path: /metrics

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8001']
    metrics_path: /metrics

  - job_name: 'task-service'
    static_configs:
      - targets: ['task-service:8002']
    metrics_path: /metrics

  - job_name: 'autoheal-engine'
    static_configs:
      - targets: ['autoheal-engine:8003']
    metrics_path: /metrics
